version: "3.8"

services:
  odm2fhir:
    image: ghcr.io/num-codex/odm2fhir:0.2.2-alpha-snapshot
    restart: "no"
    environment:
      ODM_FILE_PATH: ${ODM_FILE_PATH:-./in/demo.xml}
      ODM.REDCAP.API.URL: ${ODM_REDCAP_API_URL:-https://redcap.hospital.com/api/}
      ODM.REDCAP.API.TOKEN: ${ODM_REDCAP_API_TOKEN:-123456abcd}
      FHIR_BUNDLES_FOLDER_PATH: ${FHIR_BUNDLES_FOLDER_PATH:-./out}
      FHIR.SERVER.URL: ${FHIR_SERVER_URL:-http://fhir-gateway:8080/fhir}
      FHIR.SERVER.BASICAUTH.USERNAME: ${FHIR_SERVER_BASICAUTH_USERNAME}
      FHIR.SERVER.BASICAUTH.PASSWORD: ${FHIR_SERVER_BASICAUTH_PASSWORD}
      FHIR.SERVER.OAUTH2.TOKEN.URL: ${FHIR_SERVER_OAUTH2_TOKEN_URL}
      FHIR.SERVER.OAUTH2.CLIENT.ID: ${FHIR_SERVER_OAUTH2_CLIENT_ID}
      FHIR.SERVER.OAUTH2.CLIENT.SECRET: ${FHIR_SERVER_OAUTH2_CLIENT_SECRET}
      # CRON: ${CRON:-"0 0 0 0 * *"}
    volumes:
      # - ${ODM_FILE_PATH}:/workspace/input/ODM.xml
      - ${FHIR_BUNDLES_FOLDER_PATH}:/workspace/output
