version: "3.9" # optional since v1.27.0

services:
  i2b2-2web:
    container_name: i2b2web
    image: harbor.miracum.org/i2b2/i2b2-web:miracolix-v1.3.0
    restart: unless-stopped
    ports:
      - ${PORT_I2B2_WEB_HTTPS:-127.0.0.1:80}:80
    command: /run-httpd.sh localhost
    volumes:
      - ./i2b2_config_data.js:/var/www/html/webclient/i2b2_config_data.js:ro
    depends_on:
      - i2b2-wildfly

  i2b2-wildfly:
    container_name: i2b2wildfly
    image: harbor.miracum.org/i2b2/i2b2-wildfly:miracolix-v1.3.1
    restart: unless-stopped
    volumes:
      - ./crc.properties:/opt/jboss/wildfly/standalone/configuration/crcapp/crc.properties:ro
    depends_on:
      - i2b2-pg

  i2b2-pg:
    container_name: i2b2pg
    image: harbor.miracum.org/i2b2/i2b2-pg:miracolix-v1.3.3
    restart: unless-stopped
    ports:
      - ${PORT_I2B2_DB:-127.0.0.1:25432}:5432
    volumes:
      - pg-data-volume:/var/lib/postgresql/9.4/main

volumes:
  pg-data-volume:
