version: "3.7"

services:
  fhir-server:
    container_name: fhir-server
<<<<<<< HEAD
    # image: hapiproject/hapi:v5.1.0
    image: ghcr.io/chgl/hapi/hapi-fhir-jpaserver-starter:5.2.0-distroless
=======
    image: hapiproject/hapi:v5.1.0
>>>>>>> 1cff91b... fix: configure HAPI correctly, set HAPI as default server, fix README of HAPI server
    networks:
      - num-node
    restart: always
    ports:
<<<<<<< HEAD
      - ${PORT_HAPI_FHIR:-127.0.0.1:8082}:8080
=======
      - "8082:8080"
>>>>>>> 1cff91b... fix: configure HAPI correctly, set HAPI as default server, fix README of HAPI server
    volumes:
      - ./application.yml:/data/hapi/application.yml
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      VALIDATION_REQUESTS_ENABLED: "false"
    depends_on:
      - db

  db:
    container_name: hapidb
    image: postgres:12.4-alpine
    restart: always
    networks:
      - num-node
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

volumes:
  hapi-data: {}

networks:
  num-node:
    external: true
    name: num-node